source 'http://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0'

# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
#gem 'sqlite3'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# raven for sentry.io
gem "sentry-raven"

gem 'uglifier'
gem 'openssl', :path => '/gems/highway/ruby-openssl'
gem 'therubyracer'
gem 'sass'
gem 'sass-rails'
gem 'devise', path: '/gems/highway/devise'

# use this to get full decoding of HTTP Accept: headers, to be able to
# split off smime-type=voucher in pkcs7-mime, and other parameters
gem 'http-accept'

# used to generate multipart bodies
gem 'multipart_body', :path => '/gems/highway/multipart_body'
gem 'ecdsa',   :path => '/gems/highway/ruby_ecdsa'
gem 'chariwt', :path => '/gems/highway/ChariWTs'
gem 'jwt'

gem 'thin'
