source 'http://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0'

# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
#gem 'sqlite3'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# raven for sentry.io
gem "sentry-raven"

gem 'uglifier'
gem 'openssl', :path => '/gems/highway/ruby-openssl'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

gem 'therubyracer'
gem 'sass'
gem 'sass-rails'
gem 'devise', path: '/gems/highway/devise'

# use this to get full decoding of HTTP Accept: headers, to be able to
# split off smime-type=voucher in pkcs7-mime, and other parameters
gem 'http-accept'

# used to generate multipart bodies
gem 'multipart_body', :path => '/gems/highway/multipart_body'

gem 'ecdsa',   :path => '/gems/highway/ruby_ecdsa'

gem 'chariwt', :path => '/gems/highway/ChariWTs'
#gem 'chariwt', :git => 'https://github.com/mcr/ChariWTs.git'
gem 'jwt'

gem 'thin'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem "rspec-rails"
  gem "shoulda"
  gem 'rails-controller-testing'
end

group :development do
  # Deploy with Capistrano
  gem 'capistrano', :path => '/gems/highway/capistrano'
  gem 'capistrano-bundler', :path => '/gems/highway/bundler'
  gem 'capistrano-rails'
  gem 'capistrano-passenger', :path => '/gems/highway/passenger'
  gem 'capistrano-rvm'

  # Spring speeds up development by keeping your application running
  #  in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'sprockets', "~> 3.7.2"

  # sometimes does not get installed by default
  gem 'rb-readline'

end

